// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace celebrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526081509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "510699c3-e0b4-442c-b211-31d3d16a8181",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b35f05b7-fb24-44e7-9a04-82271b0fb33d",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscountEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DiscountStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductName");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "d7da0a39-c6f9-47be-849f-875e69a0dd2c",
                            DiscountEnd = new DateTime(2025, 6, 1, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4168),
                            DiscountStart = new DateTime(2025, 5, 27, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4159),
                            Price = 25.99m,
                            ProductImage = "mouse.jpg",
                            ProductName = "Wireless Mouse",
                            Slug = "wireless-mouse"
                        },
                        new
                        {
                            ProductId = "46327481-8470-4f66-9a71-7eaad80ce43f",
                            DiscountEnd = new DateTime(2025, 6, 2, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4180),
                            DiscountStart = new DateTime(2025, 5, 26, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4180),
                            Price = 79.99m,
                            ProductImage = "keyboard.jpg",
                            ProductName = "Mechanical Keyboard",
                            Slug = "mechanical-keyboard"
                        },
                        new
                        {
                            ProductId = "38756ba7-915b-478b-90ee-fa134c65173b",
                            DiscountEnd = new DateTime(2025, 5, 31, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4184),
                            DiscountStart = new DateTime(2025, 5, 28, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4183),
                            Price = 199.99m,
                            ProductImage = "monitor27.jpg",
                            ProductName = "HD Monitor 27\"",
                            Slug = "hd-monitor-27"
                        },
                        new
                        {
                            ProductId = "5c1bd019-e868-48d6-9bcb-2869e061eaae",
                            DiscountEnd = new DateTime(2025, 6, 5, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4203),
                            DiscountStart = new DateTime(2025, 5, 27, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4203),
                            Price = 139.50m,
                            ProductImage = "chair.jpg",
                            ProductName = "Gaming Chair",
                            Slug = "gaming-chair"
                        },
                        new
                        {
                            ProductId = "ed09b0b5-fd87-4b56-bbff-158936032289",
                            DiscountEnd = new DateTime(2025, 5, 30, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4206),
                            DiscountStart = new DateTime(2025, 5, 29, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4206),
                            Price = 45.00m,
                            ProductImage = "hub.jpg",
                            ProductName = "USB-C Hub (6-in-1)",
                            Slug = "usb-c-hub-6-in-1"
                        },
                        new
                        {
                            ProductId = "fa06c4c9-a3e5-4903-959b-c5f9ae97c452",
                            DiscountEnd = new DateTime(2025, 6, 9, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4210),
                            DiscountStart = new DateTime(2025, 5, 26, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4209),
                            Price = 59.99m,
                            ProductImage = "webcam.jpg",
                            ProductName = "1080p Webcam Pro",
                            Slug = "webcam-pro-1080p"
                        },
                        new
                        {
                            ProductId = "d2897e3b-a5de-4d45-ab34-29251bf7f7ee",
                            DiscountEnd = new DateTime(2025, 6, 1, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4254),
                            DiscountStart = new DateTime(2025, 5, 31, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4253),
                            Price = 89.95m,
                            ProductImage = "speaker.jpg",
                            ProductName = "Bluetooth Speaker",
                            Slug = "bluetooth-speaker"
                        },
                        new
                        {
                            ProductId = "6f5d1fe9-b965-45f5-90e0-bdcf724e0c73",
                            DiscountEnd = new DateTime(2025, 6, 6, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4257),
                            DiscountStart = new DateTime(2025, 6, 5, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4257),
                            Price = 129.99m,
                            ProductImage = "ssd.jpg",
                            ProductName = "External SSD 1TB",
                            Slug = "external-ssd-1tb"
                        },
                        new
                        {
                            ProductId = "f5a0fd9a-35f3-4b57-b5ff-e230eb7a301d",
                            DiscountEnd = new DateTime(2025, 5, 31, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4261),
                            DiscountStart = new DateTime(2025, 5, 27, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4260),
                            Price = 159.99m,
                            ProductImage = "headphones.jpg",
                            ProductName = "Noise-Cancelling Headphones",
                            Slug = "nc-headphones"
                        },
                        new
                        {
                            ProductId = "b93abafe-7fd2-48d1-a79c-e01b195b7fdb",
                            DiscountEnd = new DateTime(2025, 6, 25, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4264),
                            DiscountStart = new DateTime(2025, 5, 26, 8, 15, 8, 938, DateTimeKind.Utc).AddTicks(4264),
                            Price = 799.00m,
                            ProductImage = "tv.jpg",
                            ProductName = "4K Ultra HD TV",
                            Slug = "4k-ultra-hd-tv"
                        });
                });

            modelBuilder.Entity("dotnet_mvc.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dotnet_mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dotnet_mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dotnet_mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApp.Domain.Entities.Cart", b =>
                {
                    b.HasOne("MyApp.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
